credentials:
  usernames:
    admin:
      email: ben@glgaminglounges.com
      name: chud
      password: 0369

cookie:
  expiry_days: 30
  key: glg_dashboard_secret_key
  name: glg_dashboard_cookie

preauthorized:
  emails: []